# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Research Notes
tagline:             The Jekyll Butler
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nguyen Cam Tu
  url:               
  email:             ncamtu@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://ncamtu.github.io


# List of pages on bar.
pages_list:
  About: '/about'
  Archive: '/archive/'

